### ISSUE TITLE
Engine Models Fail to Run

### ISSUE THREAD

**Issue by JosephRivera1** [MrLaki5/TensorRT-ml-inference#2]
Both onnx models failed to parse when running ./ResNet50_test and ./Ultraface_test

./Ultraface_test
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format onnx2trt_onnx.ModelProto: 1:9: Message type "onnx2trt_onnx.ModelProto" has no field named "version".
Failed to parse ONNX model from file: ultraface-RFB-320.onnx
Network must have at least one output
Network validation failed.
Failed to create engine from parsed network
ImageProcessor: init: error: conversion from onnx to trt failed
Detector init failed

./ResNet50_test
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format onnx2trt_onnx.ModelProto: 1:9: Message type "onnx2trt_onnx.ModelProto" has no field named "version".
Failed to parse ONNX model from file: resnet50-v1-7.onnx
Network must have at least one output
Network validation failed.
Failed to create engine from parsed network
ImageProcessor: init: error: conversion from onnx to trt failed
Detector init failed

**Comment by MrLaki5** [comment]
Hey Joseph,

I will try to help, but I haven't maintained this repo in a while. Models are stored on git-lfs, my first guess would be that models are not fully downloaded. Can you check model sizes on your local cloned repo and write them here?

**Comment by MrLaki5** [comment]
Closing this issue, no additional comments were provided.
